"""SQLite port (Section 5.5, portability).

The approach needs three capabilities: a catalog exposing foreign keys with
their referential actions, a serializable transaction with reliable
rollback, and access to each statement's parse tree.  SQLite offers the
first two natively (PRAGMA foreign_key_list; BEGIN IMMEDIATE ... ROLLBACK
is serializable); the DELETE grammar used here is shared with PostgreSQL, so
the same pglast front end is reused.  Only the snapshot queries, the
watermark triggers and two catalog-specific invariant queries change; the
bound rules, certification gate, scope condition and decision rule are the
PostgreSQL ones, unchanged.
"""
from __future__ import annotations

import re
import shutil
import sqlite3
import time
from pathlib import Path

from .db import DATA
from .invariants import Invariant
from .snapshot import FK, Catalog, FreqCert, Snapshot
from .verifier import Verifier, VerifierConfig, StaticAnalyzer, shadow_verify


def translate_schema(sql: str) -> str:
    sql = re.sub(r"GENERATED BY DEFAULT AS IDENTITY", "", sql, flags=re.I)
    sql = re.sub(r"\bTIMESTAMPTZ\b", "TEXT", sql)
    sql = re.sub(r"DEFAULT CURRENT_TIMESTAMP", "DEFAULT (CURRENT_TIMESTAMP)", sql)
    return sql


_INFO = re.compile(r"SELECT\s+EXISTS\s*\(\s*SELECT\s+1\s+FROM\s+information_schema\.tables\s+WHERE\s+"
                   r"table_schema\s*=\s*'public'\s+AND\s+table_name\s*=\s*'(\w+)'\s*\)", re.I | re.S)


def translate_query(sql: str) -> str:
    sql = _INFO.sub(lambda m: f"SELECT EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='{m.group(1)}')", sql)
    sql = re.sub(r"\bbool_and\s*\(", "MIN(", sql, flags=re.I)
    return sql


def translate_invariants(invs):
    from dataclasses import replace
    return [replace(i, post_query=translate_query(i.post_query),
                    pre_query=translate_query(i.pre_query) if i.pre_query else None) for i in invs]


def connect(path) -> sqlite3.Connection:
    c = sqlite3.connect(str(path), isolation_level=None, check_same_thread=False)
    c.execute("PRAGMA foreign_keys = ON")
    return c


def build_fixture(fixture: str, path: Path) -> Path:
    if path.exists():
        path.unlink()
    c = connect(path)
    fdir = DATA / "fixtures" / fixture
    c.executescript(translate_schema((fdir / "schema.sql").read_text()))
    seed = re.sub(r"^SELECT setval\(.*$", "", (fdir / "seed.sql").read_text(), flags=re.M)
    c.executescript(seed)
    c.execute("CREATE TABLE ig_watermark (relname TEXT PRIMARY KEY, wm INTEGER NOT NULL)")
    for (t,) in c.execute("SELECT name FROM sqlite_master WHERE type='table' AND name <> 'ig_watermark' "
                          "AND name NOT LIKE 'sqlite%'").fetchall():
        c.execute("INSERT INTO ig_watermark VALUES (?, 1)", (t,))
        for ev in ("INSERT", "UPDATE", "DELETE"):
            c.execute(f'CREATE TRIGGER ig_wm_{ev.lower()}_{t} AFTER {ev} ON "{t}" BEGIN '
                      f"UPDATE ig_watermark SET wm = wm + 1 WHERE relname = '{t}'; END")
    c.close()
    return path


ACT = {"CASCADE": "cascade", "SET NULL": "set null", "SET DEFAULT": "set default",
       "RESTRICT": "restrict", "NO ACTION": "no action"}


def _type(decl: str) -> str:
    d = (decl or "").upper()
    if d in ("INTEGER", "BIGINT", "SMALLINT", "INT"):
        return "integer"
    if d == "TEXT":
        return "text"
    # BOOLEAN and every other declared type: SQLite stores TRUE/FALSE as 1/0,
    # so a PostgreSQL-style canonical literal would not round-trip.  Mark it
    # with a type no canonicaliser accepts, forcing the mf fallback.
    return "sqlite:" + (d.lower() or "any")


def load_catalog(c) -> Catalog:
    tables, types, fks, unique, trig = {}, {}, [], set(), set()
    names = [r[0] for r in c.execute("SELECT name FROM sqlite_master WHERE type='table' "
                                     "AND name <> 'ig_watermark' AND name NOT LIKE 'sqlite%'")]
    for t in names:
        info = c.execute(f'PRAGMA table_info("{t}")').fetchall()
        tables[t] = [r[1] for r in info]
        for r in info:
            types[(t, r[1])] = _type(r[2])
        pk = [r[1] for r in info if r[5] > 0]
        if len(pk) == 1:
            unique.add((t, pk[0]))
        groups = {}
        for row in c.execute(f'PRAGMA foreign_key_list("{t}")').fetchall():
            groups.setdefault(row[0], []).append(row)
        for gid, rows in groups.items():
            rows.sort(key=lambda r: r[1])
            parent = rows[0][2]
            pcols = tuple(r[4] for r in rows)
            if any(p is None for p in pcols):
                pinfo = c.execute(f'PRAGMA table_info("{parent}")').fetchall()
                pcols = tuple(r[1] for r in pinfo if r[5] > 0)
            fks.append(FK(f"{t}_fk{gid}", t, tuple(r[3] for r in rows), parent, pcols,
                          ACT[rows[0][6].upper()], ACT[rows[0][5].upper()]))
        for idx in c.execute(f'PRAGMA index_list("{t}")').fetchall():
            if idx[2] and not idx[4]:   # unique, not partial
                cols = c.execute(f'PRAGMA index_info("{idx[1]}")').fetchall()
                if len(cols) == 1:
                    unique.add((t, cols[0][2]))
    for (tbl, name) in c.execute("SELECT tbl_name, name FROM sqlite_master WHERE type='trigger'"):
        if not name.startswith("ig_wm_"):
            trig.add(tbl)
    return Catalog(tables, types, fks, unique, trig)


def build_snapshot(c, topk=256) -> Snapshot:
    t0 = time.perf_counter()
    cat = load_catalog(c)
    card, mf, freq, nonnull = {}, {}, {}, {}
    for t, cols in cat.tables.items():
        card[t] = c.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
        for col in cols:
            rows = c.execute(f'SELECT CAST("{col}" AS TEXT), COUNT(*) FROM "{t}" WHERE "{col}" IS NOT NULL '
                             f'GROUP BY "{col}" ORDER BY 2 DESC LIMIT {topk + 1}').fetchall()
            mf[(t, col)] = rows[0][1] if rows else 0
            complete = len(rows) <= topk
            freq[(t, col)] = FreqCert({v: n for v, n in rows[:topk]}, 0 if complete else rows[topk][1], complete)
            nonnull[(t, col)] = c.execute(f'SELECT COUNT("{col}") FROM "{t}"').fetchone()[0]
    wm = dict(c.execute("SELECT relname, wm FROM ig_watermark").fetchall())
    return Snapshot(card, mf, freq, nonnull, wm, cat, time.perf_counter() - t0)


class SQLiteVerifier(Verifier):
    def __init__(self, path, invariants, cfg: VerifierConfig | None = None):
        self.dbname = str(path)
        self.invs = translate_invariants(invariants)
        self.conn = connect(path)
        self.snap = build_snapshot(self.conn)
        self.cfg = cfg or VerifierConfig()

        def reader(t):
            r = self.conn.execute("SELECT wm FROM ig_watermark WHERE relname=?", (t,)).fetchone()
            return None if r is None else r[0]

        def read_scalar(q):
            try:
                return True, self.conn.execute(q).fetchone()[0]
            except Exception:
                return False, None

        self.static = StaticAnalyzer(self.snap, self.conn, self.cfg, reader=reader, read_scalar=read_scalar)

    def _shadow(self, statements, invs, isolation):
        return shadow_verify(self.conn, statements, invs, begin_sql="BEGIN IMMEDIATE")


def oracle_label(template: Path, invariants: list[Invariant], statements, workdir: Path):
    """Independent SQLite oracle: copy the file, commit the action, compare."""
    invs = translate_invariants(invariants)
    tmp = workdir / "oracle_clone.sqlite"
    shutil.copy(template, tmp)
    c = connect(tmp)
    try:
        def q(sql):
            try:
                return True, c.execute(sql).fetchone()[0]
            except Exception:
                return False, None
        v0 = {i.id: q(i.pre_query or i.post_query) for i in invs}
        try:
            c.execute("BEGIN")
            for s in statements:
                c.execute(s)
            c.execute("COMMIT")
        except Exception as e:
            c.execute("ROLLBACK")
            return {"label": None, "violated": [], "error": str(e)[:100]}
        bad = []
        for i in invs:
            ok, post = q(i.post_query)
            if not ok or post is None:
                if v0[i.id][0]:
                    bad.append(i.id)
                continue
            if i.is_delta:
                pre = v0[i.id][1]
                good = (pre - post) <= i.params.get("max_decrease", float("inf")) and \
                       (post - pre) <= i.params.get("max_increase", float("inf"))
            else:
                good = post == i.params.get("expected", True)
            if not good:
                bad.append(i.id)
        return {"label": "unsafe" if bad else "safe", "violated": sorted(bad), "error": None}
    finally:
        c.close()
